# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField(auto_now_add=True)),
                ('income', models.DecimalField(decimal_places=5, max_digits=10)),
                ('expense', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('target', models.DecimalField(decimal_places=5, max_digits=10)),
                ('current', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
