# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunny', '0003_auto_20161031_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='initial',
            name='amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='monthlystatus',
            name='expense',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='monthlystatus',
            name='income',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='monthlystatus',
            name='saved',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='yearlystatus',
            name='expense',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='yearlystatus',
            name='income',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='yearlystatus',
            name='saved',
            field=models.CharField(max_length=500),
        ),
    ]
