# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='head_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='ledger_head_code',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='name',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='type',
            field=models.CharField(blank=True, choices=[('ast', 'asset'), ('lib', 'liability'), ('oe', 'owners equity'), ('exp', 'expense'), ('inc', 'income')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher_number',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher_type',
            field=models.SmallIntegerField(choices=[(1, 'Purchase'), (2, 'Expense'), (3, 'Journal'), (4, 'Contra'), (5, 'Payment'), (6, 'Receipt'), (7, 'Debit note'), (8, 'Credit note')]),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='position',
            field=models.CharField(choices=[('dr', 'debit'), ('cr', 'credit')], max_length=2),
        ),
    ]
