# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170811_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='account_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='head_name', to='accounting.AccountHead'),
        ),
    ]
